# Site settings
title: SwiftTime
tagline: Time 4 Swift!
email: info [at] swiftti.me
description: > # this means to ignore newlines until "baseurl:"
  This site is about the Swift Programming Language by Apple and
  the fun of learning it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://swiftti.me" # the base hostname & protocol for your site
twitter_username: time4swift
github_username:  swifttime

# Build settings
markdown: kramdown
